INPUT_PORT  EQU 0x300
OUTPUT_PORT EQU 0x301
FAN_ON      EQU 0x01
FAN_OFF     EQU 0x00

START:
    MOV DX, INPUT_PORT
    IN AL, DX

    TEST AL, 1
    JZ FAN_OFF_STATE

FAN_ON_STATE:
    MOV DX, OUTPUT_PORT
    MOV AL, FAN_ON
    OUT DX, AL
    JMP START

FAN_OFF_STATE:
    MOV DX, OUTPUT_PORT
    MOV AL, FAN_OFF
    OUT DX, AL
    JMP START
