string = "ROOM0 -> ROOM_FRONT0 -> ROOM_FRONT1 -> ROOM_FRONT2 -> STAIR0_FLOOR0_FRONT -> STAIR0_FLOOR1_FRONT -> ROOM_FRONT3 -> ROOM_FRONT4 -> ROOM_FRONT5 -> STAIR1_FLOOR1_FRONT -> STAIR1_FLOOR2_FRONT -> ROOM_FRONT6 -> ROOM_FRONT7 -> ROOM_FRONT8 -> ROOM8"

print(len(string))
